AWSTemplateFormatVersion: '2010-09-09'

Description: This AWS CloudFormation Template configures a VPC and cloud9 instance. 

Resources:

  ModernizationVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/dacasas-aws/demos-dev-ops/main/cloudformation/vpc.yaml
    
  ModernizationCloud9:
    DependsOn: ModernizationVPC
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/dacasas-aws/demos-dev-ops/main/cloudformation/cloud9.yaml

Outputs: {}